/**
 * NC / G-code generator for Mekanika CNC Pro + PlanetCNC TNG
 *
 * Generates RS274/NGC-compliant .nc files that:
 * - Load and visualize correctly in PlanetCNC TNG software
 * - Use metric units (G21), absolute positioning (G90)
 * - Use per-slot work coordinate systems (G54–G59.2) for 8-slot fixture
 * - Generate real insole contour toolpaths (roughing + finishing)
 * - Use ball-nose cutter compensation
 * - Follow Mekanika CNC Pro safety practices
 *
 * PlanetCNC TNG requirements:
 * - Each line = one block (N-number optional)
 * - Comments in parentheses on SAME line as G-code
 * - % program delimiter at start and end
 * - Standard RS274/NGC motion codes: G0, G1, G2, G3
 * - Coordinate words: X Y Z F S
 * - Work offsets: G54-G59, G59.1, G59.2, G59.3
 * - G10 L2 Px for setting work offsets in program
 * - G4 Pn for dwell (seconds)
 */

import {
	SLOT_COORDINATE_SYSTEMS,
	type FixtureLayout,
	type CncToolSettings,
	type CncPostSettings,
	type MillingMode,
	type SlotAssignment,
	isDoubleSided,
	getStockThickness,
} from '../types';

// ──────────────────────────────────────────────
// Public API
// ──────────────────────────────────────────────

export interface GenerateNcOptions {
	millingMode: MillingMode;
	fixture: FixtureLayout;
	toolSettings: CncToolSettings;
	postSettings: CncPostSettings;
	patientName: string;
	projectId: string;
	/** Heightfield data per part (keyed by partId). If absent, generates contour-based toolpath. */
	heightfields?: Record<string, HeightfieldData>;
}

export interface HeightfieldData {
	/** Grid width (columns) */
	cols: number;
	/** Grid height (rows) */
	rows: number;
	/** Cell size in mm */
	cellSizeMm: number;
	/** Z values in mm, row-major. Z=0 is stock top surface. Negative is into the stock. */
	zValues: Float32Array | number[];
	/** Origin offset of the grid relative to the part's local (0,0) in mm */
	originOffsetMm: { x: number; y: number };
}

// ── Insole contour points ──
// Anatomically correct insole outline, ~60 points per side.
// Coordinates in mm relative to the slot origin (0,0 = block corner).
// Block is 130mm wide × 280mm long.
// Left insole occupies X≈[3,62], right X≈[68,127]. Y from 5 (toe) to 270 (heel).
//
// Left foot viewed from above:
//   Lateral edge (outside, LEFT edge) = relatively straight/convex
//   Medial edge (inside, RIGHT edge) = arch indentation in midfoot

const INSOLE_CONTOUR_LEFT: [number, number][] = [
	// ── Toe area (y 5→40) — rounded front ──
	[30, 5],
	[35, 5],
	[40, 6],
	[44, 8],
	[48, 12],
	[51, 18],
	[53, 25],
	[54, 32],
	[55, 40],
	// ── Forefoot lateral → ball of foot (y 40→90) — widest zone ──
	[56, 50],
	[57, 60],
	[58, 70],
	[58, 80],
	[57, 90],
	// ── Lateral midfoot (y 90→160) — gentle curve ──
	[56, 100],
	[55, 110],
	[54, 120],
	[53, 130],
	[52, 140],
	[51, 150],
	[50, 160],
	// ── Lateral rearfoot → heel (y 160→230) ──
	[49, 170],
	[48, 180],
	[47, 190],
	[46, 200],
	[45, 210],
	[44, 220],
	[43, 230],
	// ── Heel bottom (y 230→270) — rounded ──
	[42, 240],
	[40, 250],
	[37, 258],
	[33, 264],
	[30, 268],
	[27, 270],
	[23, 268],
	[20, 264],
	[17, 258],
	[15, 250],
	[14, 240],
	// ── Medial heel → rearfoot (y 240→160) — going back up ──
	[13, 230],
	[12, 220],
	[12, 210],
	[12, 200],
	[13, 190],
	[14, 180],
	// ── Medial ARCH zone (y 180→100) — distinctive inward curve ──
	[16, 170],
	[19, 160],
	[22, 150],
	[24, 140],
	[25, 130],
	[24, 120],
	[22, 110],
	[19, 100],
	// ── Medial forefoot (y 100→40) — widening back out ──
	[16, 90],
	[13, 80],
	[10, 70],
	[8, 60],
	[7, 50],
	[6, 40],
	// ── Medial toe (y 40→5) — closing back to start ──
	[6, 32],
	[7, 25],
	[9, 18],
	[12, 12],
	[16, 8],
	[21, 6],
	[25, 5],
];

// Right insole: mirror of left within the right half of the block (X offset by 65mm)
const INSOLE_CONTOUR_RIGHT: [number, number][] = INSOLE_CONTOUR_LEFT.map(
	([x, y]) => [130 - x, y] as [number, number]
);

/**
 * Generate a complete .nc file as a string.
 * Produces valid PlanetCNC TNG compatible G-code.
 */
export function generateNcFile(options: GenerateNcOptions): string {
	const {
		millingMode,
		fixture,
		toolSettings,
		postSettings,
		patientName,
		projectId,
		heightfields,
	} = options;

	const lines: string[] = [];
	const emit = (line: string) => lines.push(line);

	// ── Program start ──
	emit('%');
	emit('(Mekanika CNC Pro - PlanetCNC TNG)');
	emit(`(Patient: ${patientName})`);
	emit(`(Project: ${projectId})`);
	emit(`(Mode: ${millingMode})`);
	emit(`(Date: ${new Date().toISOString().slice(0, 10)})`);
	emit('(Generated by PODO v1.0)');
	emit('');

	// ── Safety / initialization ──
	emit('G90 (Absolute positioning)');
	emit('G21 (Metric - millimeters)');
	emit('G17 (XY plane select)');
	emit('G94 (Feed rate in mm/min)');
	emit('G40 (Cancel cutter compensation)');
	emit('G49 (Cancel tool length offset)');
	emit('G80 (Cancel canned cycles)');
	emit('');

	// ── Tool selection ──
	emit('T1 M6 (Select tool 1)');
	emit(`(Tool: ${toolSettings.toolType} D=${toolSettings.toolDiameterMm}mm)`);
	emit(`S${toolSettings.spindleSpeedRpm} M3 (Spindle ON CW at ${toolSettings.spindleSpeedRpm} RPM)`);
	emit('G4 P5 (Dwell 5s - wait for spindle speed)');
	emit('');

	// ── Embed fixture offsets ──
	if (postSettings.embedOffsets) {
		emit('(--- Fixture slot offsets ---)');
		for (let i = 0; i < fixture.slotCount; i++) {
			const offset = fixture.slotOffsets[i];
			if (!offset) continue;
			const pNumber = coordinateSystemToPNumber(i);
			emit(`G10 L2 P${pNumber} X${fmt(offset.x)} Y${fmt(offset.y)} Z${fmt(offset.z)}`);
		}
		emit('');
	}

	// ── Per-slot toolpaths ──
	const sortedAssignments = [...fixture.assignments].sort(
		(a, b) => a.slotIndex - b.slotIndex
	);

	if (sortedAssignments.length === 0) {
		emit('(WARNING: No slots assigned - empty program)');
		emit(`G0 Z${fmt(toolSettings.safeZMm)} (Retract to safe Z)`);
		emit('M5 (Spindle OFF)');
		emit(`${postSettings.programEnd} (Program end)`);
		emit('%');
		return lines.join('\n');
	}

	for (const assignment of sortedAssignments) {
		emitSlotProgram(
			lines,
			assignment,
			toolSettings,
			millingMode,
			heightfields?.[assignment.partId] ?? null
		);
	}

	// ── Double-sided: pause for flip ──
	if (isDoubleSided(millingMode)) {
		emit('');
		emit('(========================================)');
		emit('(FLIP STOCK - dubbelzijdig frezen)');
		const thickness = getStockThickness(millingMode);
		if (thickness) emit(`(Blok dikte: ${thickness}mm)`);
		emit('(Draai alle EVA blokken om en herpositioneer)');
		emit('(Controleer Z-nulpunt na het omdraaien)');
		emit('(========================================)');
		emit('M0 (Programma pauze - draai blokken om)');
		emit('');

		emit('(--- Bottom side passes ---)');
		for (const assignment of sortedAssignments) {
			emitSlotProgram(lines, assignment, toolSettings, millingMode, null, 'bottom');
		}
	}

	// ── Program end ──
	emit('');
	emit('(--- Program end ---)');
	emit(`G0 Z${fmt(toolSettings.safeZMm)} (Retract to safe Z)`);
	emit('G0 X0 Y0 (Return to origin)');
	emit('M5 (Spindle OFF)');
	emit(`${postSettings.programEnd} (Program end)`);
	emit('%');

	return lines.join('\n');
}

/**
 * Download a .nc file in the browser.
 */
export function downloadNcFile(content: string, filename: string): void {
	const blob = new Blob([content], { type: 'text/plain' });
	const url = URL.createObjectURL(blob);
	const a = document.createElement('a');
	a.href = url;
	a.download = filename;
	a.style.display = 'none';
	document.body.appendChild(a);
	a.click();
	document.body.removeChild(a);
	setTimeout(() => URL.revokeObjectURL(url), 100);
}

// ──────────────────────────────────────────────
// Internal helpers
// ──────────────────────────────────────────────

function emitSlotProgram(
	lines: string[],
	assignment: SlotAssignment,
	tool: CncToolSettings,
	_millingMode: MillingMode,
	heightfield: HeightfieldData | null,
	side: 'top' | 'bottom' = 'top'
): void {
	const emit = (line: string) => lines.push(line);
	const coordSys = SLOT_COORDINATE_SYSTEMS[assignment.slotIndex] ?? 'G54';
	const contour = assignment.partId === 'left' ? INSOLE_CONTOUR_LEFT : INSOLE_CONTOUR_RIGHT;

	emit('');
	emit(`(==== Slot ${assignment.slotIndex + 1} - ${assignment.label} [${side}] ====)`);
	emit(`${coordSys} (Select work offset for slot ${assignment.slotIndex + 1})`);
	emit(`G0 Z${fmt(tool.safeZMm)} (Safe Z)`);
	emit('G0 X0 Y0 (Rapid to slot origin)');
	emit('');

	if (heightfield) {
		emitRasterFinishPass(lines, heightfield, tool);
	} else {
		// Generate real insole contour toolpath
		emitInsoleContourToolpath(lines, contour, tool, side);
	}

	emit(`G0 Z${fmt(tool.safeZMm)} (Retract after slot ${assignment.slotIndex + 1})`);
}

/**
 * Generate a full insole milling toolpath from contour points.
 * 1. Roughing passes — zigzag raster pocket clearing at incremental Z depths
 * 2. Finish contour pass at final depth
 * 3. Spring pass — repeat contour for surface quality
 *
 * This generates G1 cutting moves that PlanetCNC TNG displays as toolpath lines.
 */
function emitInsoleContourToolpath(
	lines: string[],
	contour: [number, number][],
	tool: CncToolSettings,
	side: 'top' | 'bottom'
): void {
	const emit = (line: string) => lines.push(line);

	// Compute bounding box from the actual contour
	let minY = Infinity, maxY = -Infinity;
	for (const [, cy] of contour) {
		if (cy < minY) minY = cy;
		if (cy > maxY) maxY = cy;
	}
	const insoleH = maxY - minY;
	const totalDepth = side === 'top' ? 15 : 10;
	const depthPerPass = tool.depthOfCutMm;
	const finishAllowance = 0.3;
	const stepover = (tool.toolDiameterMm * tool.stepoverPercent) / 100;
	const numRoughPasses = Math.ceil((totalDepth - finishAllowance) / depthPerPass);

	// ── Roughing passes ──
	emit(`(--- Roughing: ${numRoughPasses} passes, DOC=${depthPerPass}mm ---)`);

	for (let pass = 1; pass <= numRoughPasses; pass++) {
		const zDepth = -Math.min(pass * depthPerPass, totalDepth - finishAllowance);
		emit(`(Rough pass ${pass}/${numRoughPasses} at Z=${fmt(zDepth)})`);
		emit(`G0 Z${fmt(tool.safeZMm)}`);

		let zigzag = false;
		const margin = tool.toolDiameterMm / 2 + 1;

		for (let y = minY + margin; y < maxY - margin; y += stepover) {
			const xRange = getContourXRange(contour, y, margin);
			if (!xRange) continue;
			const [xMin, xMax] = xRange;

			if (!zigzag) {
				emit(`G0 X${fmt(xMin)} Y${fmt(y)}`);
				emit(`G1 Z${fmt(zDepth)} F${tool.feedRateZMmMin}`);
				emit(`G1 X${fmt(xMax)} Y${fmt(y)} F${tool.feedRateXYMmMin}`);
			} else {
				emit(`G0 X${fmt(xMax)} Y${fmt(y)}`);
				emit(`G1 Z${fmt(zDepth)} F${tool.feedRateZMmMin}`);
				emit(`G1 X${fmt(xMin)} Y${fmt(y)} F${tool.feedRateXYMmMin}`);
			}
			zigzag = !zigzag;
		}
		emit(`G0 Z${fmt(tool.safeZMm)}`);
	}

	// ── Finish contour pass ──
	const finishZ = -totalDepth;
	const finishFeed = Math.round(tool.feedRateXYMmMin * 0.6);

	emit('');
	emit(`(--- Finish contour pass at Z=${fmt(finishZ)} ---)`);
	emit(`G0 Z${fmt(tool.safeZMm)}`);

	const [startX, startY] = contour[0];
	emit(`G0 X${fmt(startX)} Y${fmt(startY)}`);
	emit(`G1 Z${fmt(finishZ)} F${tool.feedRateZMmMin} (Plunge to finish depth)`);

	for (let i = 1; i < contour.length; i++) {
		const [cx, cy] = contour[i];
		emit(`G1 X${fmt(cx)} Y${fmt(cy)} F${finishFeed}`);
	}
	emit(`G1 X${fmt(startX)} Y${fmt(startY)} F${finishFeed} (Close contour)`);

	// Spring pass
	emit('(Spring pass - repeat contour for surface finish)');
	for (let i = 1; i < contour.length; i++) {
		const [cx, cy] = contour[i];
		emit(`G1 X${fmt(cx)} Y${fmt(cy)} F${finishFeed}`);
	}
	emit(`G1 X${fmt(startX)} Y${fmt(startY)} F${finishFeed}`);
	emit(`G0 Z${fmt(tool.safeZMm)}`);
}

/**
 * Find the X range where a horizontal Y-line intersects the insole contour.
 */
function getContourXRange(
	contour: [number, number][],
	y: number,
	margin: number
): [number, number] | null {
	const intersections: number[] = [];

	for (let i = 0; i < contour.length; i++) {
		const [x1, y1] = contour[i];
		const [x2, y2] = contour[(i + 1) % contour.length];
		if ((y1 <= y && y2 >= y) || (y2 <= y && y1 >= y)) {
			if (Math.abs(y2 - y1) < 0.001) continue;
			const t = (y - y1) / (y2 - y1);
			intersections.push(x1 + t * (x2 - x1));
		}
	}

	if (intersections.length < 2) return null;
	const xMin = Math.min(...intersections) + margin;
	const xMax = Math.max(...intersections) - margin;
	return xMax > xMin ? [xMin, xMax] : null;
}

/**
 * Emit a raster finishing pass from heightfield data.
 */
function emitRasterFinishPass(
	lines: string[],
	hf: HeightfieldData,
	tool: CncToolSettings
): void {
	const emit = (line: string) => lines.push(line);
	const stepoverMm = (tool.toolDiameterMm * tool.stepoverPercent) / 100;
	const ballNoseRadius = tool.toolType === 'ball-nose' ? tool.toolDiameterMm / 2 : 0;

	emit(`(Raster finish: ${hf.cols}x${hf.rows} grid, cell=${hf.cellSizeMm}mm, stepover=${stepoverMm.toFixed(2)}mm)`);

	const rowStep = Math.max(1, Math.round(stepoverMm / hf.cellSizeMm));
	let zigzag = false;

	for (let row = 0; row < hf.rows; row += rowStep) {
		const y = hf.originOffsetMm.y + row * hf.cellSizeMm;
		const startCol = zigzag ? hf.cols - 1 : 0;
		const startX = hf.originOffsetMm.x + startCol * hf.cellSizeMm;
		emit(`G0 X${fmt(startX)} Y${fmt(y)}`);

		const firstZ = getHeightfieldZ(hf, row, startCol) + ballNoseRadius;
		emit(`G1 Z${fmt(firstZ)} F${tool.feedRateZMmMin}`);

		const colStart = zigzag ? hf.cols - 2 : 1;
		const colEnd = zigzag ? -1 : hf.cols;
		const colDir = zigzag ? -1 : 1;

		for (let col = colStart; col !== colEnd; col += colDir) {
			const x = hf.originOffsetMm.x + col * hf.cellSizeMm;
			const z = getHeightfieldZ(hf, row, col) + ballNoseRadius;
			emit(`G1 X${fmt(x)} Y${fmt(y)} Z${fmt(z)} F${tool.feedRateXYMmMin}`);
		}
		emit(`G0 Z${fmt(tool.safeZMm)}`);
		zigzag = !zigzag;
	}
}

function getHeightfieldZ(hf: HeightfieldData, row: number, col: number): number {
	const idx = row * hf.cols + col;
	const val = hf.zValues[idx];
	return typeof val === 'number' && Number.isFinite(val) ? val : 0;
}

function coordinateSystemToPNumber(slotIndex: number): number {
	return slotIndex + 1;
}

function fmt(value: number): string {
	return value.toFixed(3);
}
